version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    volumes:
      - /root/don/data/wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress
    restart: always
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/don/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/don/conf/nginx/conf/conf.d:/etc/nginx/conf.d
      - /root/don/conf/nginx/logs:/var/log/nginx
    restart: always
    depends_on:
      - wordpress
      - springboot
  springboot:
    image: qdt
    ports:
      - "8080:8080"
    restart: always
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - /root/don/data/mysql:/var/lib/mysql
    restart: always
